
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::128759047428:role/eksctl-expense-2-nodegroup-ng-1-NodeInstanceRole-FWs2sSwOPvhq
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::128759047428:user/suresh
      username: suresh
    - groups:
      - expense-admin
      userarn: arn:aws:iam::128759047428:user/ramesh
      username: ramesh
    
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-02T09:35:22Z"
  name: aws-auth
  namespace: kube-system
  uid: 2d0bb2fe-f3d1-4cbc-87d6-8807c15f0603

